

 `NumPy is a powerful library for scientific computing in Python.` 
 `In this notebook, we'll explore the important functions of NumPy used in Python.`




In [1]:
import numpy as np # Importing numpy library
print(np.__version__) # Printing the version of numpy library

1.26.4


In [2]:
a=np.array([4,5,6]) #this will create a 1D array
print(a) #this will print the array


[4 5 6]


In [3]:
print(a.shape)  #this will give the shape of the array. it will give the number of elements in the array. it give value in tuple.

(3,)


In [4]:
print(a.dtype) #this will give the data type of the array. it will give the data type of the elements in the array.

int32


In [5]:
print(a.ndim) #this will give the dimension of the array. it will give the number of dimensions of the array.

1


In [6]:
print(a.size) #this will give the size of the array. it will give the number of elements in the array.

3


In [7]:
print(a.itemsize) #this will give the size of the elements in the array. it will give the size of the elements in the array. it will give the size in bytes.

4


In [8]:
print(a[0]) #this will give the element at 0th index.

4


In [9]:
a[0]=11 #this will change the element at 0th index to 11.

In [10]:
print(a)

[11  5  6]


In [11]:
b = a * np.array([1,0,1])  #this will multiply the array a with the array [1,0,1] element wise.

print(b) #this will print the array b.

[11  0  6]


In [12]:
l = [1,2,3] #this will create a list l.
a= np.array([1,2,3])


#if we apply append here it will append the element at the end of the list, but append will not work in numpy array.

In [13]:
l= l+[4] #this will append 4 at the end of the list l.
print(l) 

a=a+np.array([4]) #this will add 4 to each element of the array a. broadcasting is happening here.
print(a)

#a=a+np.array([4,4,4]) # this will also give the same result as above when only one 4 is given. numpy is intelligent enough to understand the broadcasting.

[1, 2, 3, 4]
[5 6 7]


In [14]:
l = l*2 #this will multiply the list l by 2. it will repeat the list l 2 times.
print(l)

a=a * 2 #this will multiply the array a by 2. it will multiply each element of the array by 2.
print(a)

[1, 2, 3, 4, 1, 2, 3, 4]
[10 12 14]


In [15]:
a = np.sqrt(a) #this will take the square root of each element of the array a.
print(a)

#this will keep the size of the array same. it will not change the size of the array.

[3.16227766 3.46410162 3.74165739]


In [16]:
a= np.log(a) #this will take the log of each element of the array a.
print(a)

# it will not change the size of the array.

[1.15129255 1.24245332 1.31952866]


#### Dot product using `np.dot() ` method.

<p>dot product is the sum of the product of the corresponding elements of the two arrays.</p>

#### dot product in _lists_.👇

In [17]:


l1 = [1,2,3] #this will create a list l1.
l2 = [4,5,6] #this will create a list l2.



#dot product
dot = 0

for i in range (len(l1)):
    dot+= l1[i]*l2[i]
print(dot)

32


#### dot product in _arrays_

In [18]:
#


a1 = np.array(l1) #this will create an array a1 from the list l1.
a2 = np. array(l2) #this will create an array a2 from the list l2.

dot = np.dot(a1,a2) #this will give the dot product of the arrays a1 and a2.
print(dot)

32


In [19]:
sum1 = a1*a2 #this will give the element wise product of the arrays a1 and a2.
dot = (sum1).sum() #this will give the sum of the elements of the array dot.
print(dot)

32


#### Dot product using `@` sign.

In [20]:
dot = a1 @ a2 #this will give the dot product of the arrays a1 and a2.
print(dot) 

32


### Multidimensional (nd) arrays:- 


In [21]:
a = np.array([[1,2],[4,5]]) #this will create a 2D array a. notice the number of square brackets.
print(a)


[[1 2]
 [4 5]]


In [22]:
print(a.shape) #this will give the shape of the array a. it will give the number of rows and columns in the array. it will give the value in tuple.

(2, 2)


In [23]:
print(a[0])

[1 2]


In [24]:
print(a[0][1])

2


In [25]:
#we can also write the previous two lines in the following way and get the same result.
print(a[0,1])

2


### _slicing in 2D array_.

<p>this means we can get the sub array from the array.
slicing has in the format [start:stop:step]

slicing has the foramt [start:stop:step]. if we don't give the start, stop and step, it will take the default values. default values are start=0, stop=last element, step=1.
 </p>



In [26]:
b = a[0,1] #this will give the element at 0th row and 1st column.this is how indexing is done in numpy. indexing starts from 0. -1 is the last element.
print(b)

c= a[0,:1] #this works as slicing. it will give the 0th row and all the columns. blank space before and after : means all the elements.
print(c)

2
[1]


In [27]:
print(a.T) #this will give the transpose of the array a.

[[1 4]
 [2 5]]


In [28]:
print(a.T.shape) #this will give the shape of the transpose of the array a.

(2, 2)


In [29]:
print(np.linalg.inv(a)) #this will give the inverse of the array a.
print(a)

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
[[1 2]
 [4 5]]


In [30]:
print(np.linalg.det(a)) #this will give the determinant of the array a.
print(a)

-2.9999999999999996
[[1 2]
 [4 5]]


In [31]:
print(np.diag(a)) #this will give the diagonal of the array a. it will give the diagonal elements in the form of an array.

[1 5]


### boolean indexing

##### traditional boolean indexing

In [32]:
bi = np.array([[1,2],[3,4],[5,6]])
print(bi)

bool_idx = (bi>2) #this will give the boolean array. it will give True if the element is greater than 2 and False if the element is less than or equal to 2.
print(bool_idx)

print(bi[bool_idx]) #this will give the elements of the array a which are greater than 2.

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [33]:
#we can also write the above two lines in the following way and get the same result.
print(bi[bi>2])  #this will give the elements of the array a which are greater than 2. 

[3 4 5 6]


In [34]:
w= np.where(bi>2, bi, 404) #this will give the elements of the array bi which are greater than 2. if the element is less than or equal to 2, it will give 404.
#if we breakdown the syntax of where function, it is where(condition to be checked, value to be returned if the condition is true, value to be returned if the condition is false).
print(w)

[[404 404]
 [  3   4]
 [  5   6]]


__fancy indexing__
##### fancy indexing is used when we want to select the elements of the array at the indexes we want.

- we can pass the indexes in the form of a list and will get the elements at those indexes. 
- we can also pass the indexes in the form of a boolean array and will get the elements at the indexes where the boolean array is True.
- we can also pass the indexes in the form of a 2D array and  will get the elements at the indexes of the 2D array.

In [35]:
a = np.array([12,34,54,18,76,98])
b = [1,4,5]

print(a[b]) #this will give the elements of the array a at the indexes 1,4 and 5.

[34 76 98]


In [36]:
a = np.array([12,34,54,18,76,98])


even = np.argwhere(a%2==0).flatten() #this will give the indexes of the elements of the array a which are even. flatten will convert the 2D array to 1D array.
print(even)
print(a[even])

[0 1 2 3 4 5]
[12 34 54 18 76 98]


### Reshaping

- reshaping  is used when we want to change the shape of the array. 
- it is used to change the shape of the array without changing the data of the array.
- it is used when our model requires the data to be shaped in a particular way and 
- it is used to change the shape of the array without changing the data of the array.

In [37]:
y= np.arange(2,8) #this will give the array of elements from 2 to 8. format of arange function is arange(start, stop, step).
print(y)
print(y.shape)

z= y.reshape(2,3) #this will reshape the array y to 2 rows and 3 columns. but this will show error if the number of elements in the array and the number of elements in the reshape function are not equal.
print(z)

[2 3 4 5 6 7]
(6,)
[[2 3 4]
 [5 6 7]]


In [38]:
# new axis is used when our model requires the data to be shaped in a particular way. it is used to increase the dimension of the array.
# add new axis to the end of the array

a = np.array([1,2,3,4,5,6]) 

b = a[np.newaxis, :] #this will add a new axis at the beginning of the array a. it will convert the 1D array to 2D array.
# lets breakdown how the newaxis works. if we have a 1D array of 6 elements, then the shape of the array will be (6,). if we add a new axis at the beginning of the array, then the shape of the array will be (1,6).
print(b.shape)



# we can also do that in the following way.
b=a[: ,np.newaxis]
print(b.shape)

(1, 6)
(6, 1)


### Concatenating arrays using `np.concatenate()` method

In [39]:
f = np.array([[1,2],[5,6]])
g = np.array([[7,8]])

h = np.concatenate((f,g)) #this will concatenate the arrays f and g. it will concatenate the arrays row wise. 
print(h)




[[1 2]
 [5 6]
 [7 8]]


In [40]:
i = np.concatenate((f,g),axis = None)  # with axis = None it will flatten the array. it will concatenate the arrays column wise. and it will give the 1D array.
print(i)

[1 2 5 6 7 8]


In [41]:
j = np.concatenate((f,g),axis = 0) #this will concatenate the arrays f and g. it will concatenate the arrays row wise. axis = 0 is default. 
print(j)

#axis = 0 means row wise concatenation. and it axis =1 means column wise concatenation.

[[1 2]
 [5 6]
 [7 8]]


In [42]:
k=np.concatenate((f,g.T), axis = 1) #this will concatenate the arrays f and g. it will concatenate the arrays column wise. )
print(k)

[[1 2 7]
 [5 6 8]]


#### Concatenating arrays using `np.hstack()` and `np.vstack()` methods

`np.hstack()` concatenates the array horizontally (_row wise_) <br>
`np.vstack()` concatenates the array vertically (_column wise_) <br>
 

In [43]:
#applying np.hstack and np.vstack in 1 D array will give the same result as np.concatenate. difference is that hstack and vstack are used for 2D arrays.


a1 = np.array([1,2])
a2 = np.array([3,4])


a3 = np.hstack((a1,a2))  #this will concatenate the arrays a1 and a2. it will concatenate the arrays row wise.
print(a3)

a4 = np.vstack((a1,a2)) #this will concatenate the arrays a1 and a2. it will concatenate the arrays column wise.
print(a4)

[1 2 3 4]
[[1 2]
 [3 4]]


In [44]:
#broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.


b1 = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
b2 = np.array([2,3,2]) #numpy is intelligent enough to understand the broadcasting. it will add the array b2 to each row of the array b1. and we need not to write three arrays in b2 to get the result.


b3 = b1+b2 #this will add the array b2 to each row of the array b1. broadcasting is happening here. 
b3

array([[ 3,  5,  5],
       [ 6,  8,  8],
       [ 9, 11, 11]])

In [45]:
b4 = b2 +  2
b4

array([4, 5, 4])

In [46]:
b5 = b4 - 8
b5

array([-4, -3, -4])

In [47]:
b6 = b5 * 2
b6

array([-8, -6, -8])

#### Using `.sum()` function in numpy

In [48]:
b1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
print(b1.sum())
print(b1.sum(axis = None))  #this will give the sum of all the elements of the array b1. axis = None is default.
 

45
45


In [50]:
print(b1.sum(axis = 0)) #this will give the sum of the elements of the array b1 column wise.
print(b1.sum(0))

[12 15 18]
[12 15 18]


In [51]:
print(b1.sum(axis = 1)) #this will give the sum of the elements of the array b1 row wise.
print(b1.sum(1))

[ 6 15 24]
[ 6 15 24]


#### Using `.mean()` function in numpy


In [52]:
print(b1.mean()) #this will give the mean of all the elements of the array b1.
print(b1.mean(axis = None)) 

5.0
5.0


In [53]:
print(b1.mean(0))
print(b1.mean(axis = 0)) #this will give the mean of the elements of the array b1 column wise.

[4. 5. 6.]
[4. 5. 6.]


In [54]:
print(b1.mean(1))
print(b1.mean(axis=1)) #this will give the mean of the elements of the array b1 row wise.

[2. 5. 8.]
[2. 5. 8.]


Some more data science function var, std, min , max, 

In [55]:
print(b1.var(axis = None))

6.666666666666667


In [56]:
print(b1.std(axis = None))
print(np.std(b1,axis = None))

2.581988897471611
2.581988897471611


In [57]:
print(b1.min(axis = None))
print(np.min(b1,axis=None))

1
1


In [58]:
print(b1.max(axis = None))
print(np.max(b1,axis= None))

9
9


##### Datatypes

In [59]:
c1 = np.array([[1,2],[3,4]])
print(c1.dtype)

int32


In [60]:
c2 = np.array([[1.1,2.0],[3.3,4.0]])
print(c2.dtype)

float64


In [61]:
c3 = c1 + c2
print(c3.dtype)

float64


In [62]:
c4 = np.array([1,2,3], dtype=np.float64)
print(c4.dtype)
c4

float64


array([1., 2., 3.])

#### Copying Arrays

In [63]:
z1 = np.array([1,2,3,4,5,6])
z2 = z1
z2[0] = 100
z2

array([100,   2,   3,   4,   5,   6])

In [64]:
#we have changed only the value of z2 but the value of z1 has also changed. 
#this is because z1 and z2 are pointing to the same memory location. 
#so if we change the value of z2, the value of z1 will also change. reference is being passed here.
#to avoid this we can use the copy function.

z1

array([100,   2,   3,   4,   5,   6])

#### Using `.copy()` method

In [65]:
# if we want an actual copy, we have to use the .copy() method.

z4 = np.array([5,6,7,8,9,10])
z3 = z4.copy()
z3[0] = 100

print(z3)
print(z4)

[100   6   7   8   9  10]
[ 5  6  7  8  9 10]


#### Generating Arrays

#### Using `.zeros()` method

In [66]:
g1 = np.zeros((2,3)) #this will create a 2D array of 2 rows and 3 columns with all the elements as 0.
g1

array([[0., 0., 0.],
       [0., 0., 0.]])

#### Using `.ones()` method

In [67]:
g2 = np.ones((2,3)) #this will create a 2D array of 2 rows and 3 columns with all the elements as 1.
g2

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Using `.full()` method

In [68]:
g3 = np.full((2,3), 7) #this will create a 2D array of 2 rows and 3 columns with all the elements as 7.
g3

array([[7, 7, 7],
       [7, 7, 7]])

#### Using `.eye()` method

In [69]:
g4 = np.eye(12) #this will create a 2D array of 12 rows and 12 columns with diagonal elements as 1 and rest of the elements as 0.
g4

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#### Using `.arange()` method

In [70]:
g5 = np.arange(12) #this will create a 1D array of elements from 0 to 11.
g5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### Using `.linspace()`  method

In [71]:
g6 = np.linspace(1,10,5) #this will create an array of 5 elements from 1 to 10. it will divide the range 1 to 10 into 5 equal parts.
g6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#### Random Numbers

In [72]:
r1 = np.random.random((2,3)) #this will create a 2D array of 2 rows and 3 columns with random elements between 0 and 1.
r1

array([[0.08317229, 0.93935326, 0.75474849],
       [0.77680737, 0.11769758, 0.78537928]])

In [73]:
r2 = np.random.randint(1,10, (2,3)) #this will create a 2D array of 2 rows and 3 columns with random elements between 1 and 10.
r2

array([[9, 7, 4],
       [1, 3, 8]])

In [74]:
r4 = np.random.randint(5, size =(3,3)) #this will create a 2D array of 2 rows and 3 columns with random elements between 0 and 10. if not given two numbers, it will take the first number as 0.
print(r4)

[[0 1 2]
 [4 3 4]
 [3 3 3]]


In [75]:
r3 = np.random.randn(2,3) #this will create a 2D array of 2 rows and 3 columns with random elements from standard normal distribution.
r3
#print(a.mean(), a.var())

array([[-0.13973147, -0.42559521, -0.88380608],
       [ 0.53975022, -0.79473302,  0.51316182]])

In [76]:
r5 = np.random.randn (500)
print(r5.mean(), r5.var()) #mean and variance of array r is close to 0 and 1 respectively because the random numbers are generated from standard normal distribution. also known as gaussian distribution.

0.1414949727377623 1.007166589904994


In [77]:
r6 = np.random.choice(7, size= (2,3)) 
r6

array([[2, 6, 2],
       [0, 3, 1]])

In [78]:
r7 = np.random.choice([1,2,3,4,5], size = (2,3)) 
r7

array([[2, 1, 2],
       [3, 5, 4]])

### Efficient and Readable Method for Importing Arrays from Custom CSV Formats

In [79]:
data = np.genfromtxt("./data.csv", delimiter=",", dtype=np.float32)
data.shape


#here we have loaded the data from the csv file. we have given the path of the file, delimiter and the data type of the elements in the file.
#delimiter is used to separate the elements in the file. here we have used comma as the delimiter.
#dtype is used to specify the data type of the elements in the file. here we have used float32 as the data type.
#shape is used to give the shape of the array. it will give the number of rows and columns in the array. it will give the value in tuple.


(100, 28)

In [80]:

#we can also use the following code to load the data from the csv file.

data1 = np.loadtxt("./data.csv", delimiter=",", dtype=np.float32)
data1.shape


#only difference between genfromtxt and loadtxt is that genfromtxt can handle missing values and loadtxt cannot handle missing values.
# genfromtxt is more flexible than loadtxt.
# genfromtxt is slower than loadtxt.
# genfromtxt is more memory intensive than loadtxt.
# genfromtxt offers more options for parameters.

(100, 28)

#### Eigenvector and EigenValues

In [81]:
# a vector that undergoes pure scaling without any rotation is known as eigenvector.
# the scalar that scales the eigenvector is known as eigenvalue.
# eigenvectors are used in PCA, image compression, face recognition, etc.
# eigenvectors are used to find the principal components of the data.
# eigenvectors are used to find the directions of maximum variance in the data.
# the eigenvectors are the directions along which a particular linear transformation acts by flipping, compressing or stretching.

In [82]:
a = np. array( [ [1, 2] ,[3,4]])
eigenvalues, eigenvectors = np. linalg.eig(a)
#print(eigenvalues)
#print(eigenvectors) # column vecotr!
# e vec * e val = A * e vec
b = eigenvectors[:,0] * eigenvalues[0]
print(b)
c = a @ eigenvectors[:,0]
print(b)
#print(b==c)
print(np.allclose(b,c)) # this will give True if all the elements of b and c are same, otherwise it will give False.

[ 0.30697009 -0.21062466]
[ 0.30697009 -0.21062466]
True


### Iterate numpy array using nditer

In [83]:
n1 = np.arange(9).reshape(3,3)
n1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [84]:
for row in n1: #this will print the rows of the array n1.
    print(row)
  

[0 1 2]
[3 4 5]
[6 7 8]


In [85]:
for row in n1:
    for cell in row: #this will give the elements of the array n1 row wise.
        print(cell)

0
1
2
3
4
5
6
7
8


### flattening the array into list

here we don't need to write two `for` loops as above. we can do the above using one single `for` loop

In [86]:

# difference in .flat and .flatten() is that .flat is an attribute and .flatten() is a method.

for cell in n1.flat: 
    print(cell)

print("\n")

for cell in n1.flatten(): 
    print(cell)

0
1
2
3
4
5
6
7
8


0
1
2
3
4
5
6
7
8


### Using `numpy.nditer` function


#### nditer is used to iterate over the elements of the array. it is faster than the above methods. 
#### it is used to iterate over the elements of the array in a more efficient way. 


**Order:**
1. C order to iterate over each row and each column
2. F (fortan) order to iterate over each column and each row

![C and Fortan order](c-fortan.jpg)

In [87]:

for ni1 in np.nditer(n1,order='C'): #this will iterate over the elements of the array n1 row wise.[C means row wise]
    print(ni1)

0
1
2
3
4
5
6
7
8


In [88]:
for ni2 in np.nditer(n1,order='F'): #this will iterate over the elements of the array n1 column wise. [Fortran order.]
    print(ni2)

0
3
6
1
4
7
2
5
8


In [89]:
#external loop here is used to iterate over the entire column instesad of individual elements.
for ni3 in np.nditer(n1,order='F',flags=['external_loop']): #this will iterate over the elements of the array n1 column wise. [Fortran order.]
    print(ni3)

[0 3 6]
[1 4 7]
[2 5 8]


In [90]:
for ni4 in np.nditer(n1,op_flags=['readwrite']): #this will iterate over the elements of the array n1 and we can change the elements of the array n1.
    ni4[...] = ni4 * ni4 #this will square the elements of the array n1.

print(n1)

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [91]:
n2 = np.arange(10, 19,1).reshape(3, 3)
n2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [92]:
#loop through both arrays at the same time.

for i,j in np.nditer([n1,n2]): #this will iterate over the elements of the arrays n1 and n2 at the same time.
    print(i,j)

0 10
1 11
4 12
9 13
16 14
25 15
36 16
49 17
64 18


In [93]:
z = np.array(
    [np.arange(1,7).reshape(2,3),
              np.arange(11,17).reshape(2,3),
              np.arange(7,13).reshape(2,3),
              np.arange(16,22).reshape(2,3)]
              )

z

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[16, 17, 18],
        [19, 20, 21]]])